# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
# Import city_data_df from Part 1 as CSV file

new_df = pd.read_csv("../starter_code/city_data_df.csv")
new_df

,Unnamed: 0,City,Latitude,Longitude,Max Temperature,Humidity,Cloudiness,Wind Speed,Country
0,0,taltal,-25.4000,-70.4833,66.43,71,8,3.51,CL
1,1,new norfolk,-42.7826,147.0587,68.00,77,75,10.36,AU
2,2,avarua,-21.2078,-159.7750,86.00,66,20,10.36,CK
3,3,mar del plata,-38.0023,-57.5575,66.99,82,20,9.22,AR
4,4,ponta do sol,32.6667,-17.1000,53.01,70,11,5.01,PT
...,...,...,...,...,...,...,...,...,...
577,577,vila velha,-20.3297,-40.2925,78.80,83,20,8.05,BR
578,578,la paz,-16.5000,-68.1500,48.20,81,75,3.44,BO
579,579,outlook,51.5001,-107.0513,-0.99,78,86,11.50,CA
580,580,quelimane,-17.8786,36.8883,82.40,89,40,2.73,MZ
581,581,dukhovnitskoye,52.4828,48.2137,33.13,96,100,8.52,RU

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
# Configure gmaps
gmaps.configure(api_key=g_key)

In [4]:
# Store latitude/longitude as locations
locations = new_df[['Latitude', 'Longitude']].astype(float)

# Store as humidity_complete
humidity_complete = new_df['Humidity'].astype(float)

In [14]:
figure_layout = {
    'width': '900px',
    'height': '600px',
    'border': '1px solid black',
    'padding': '1px',
    'margin': '0 auto 0 auto'
}


fig = gmaps.figure()

heat_layer = gmaps.heatmap_layer(locations, weights=humidity_complete, 
                                 dissipating=False, max_intensity=100,
                                 point_radius = 4)

fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [34]:
# Create dataframe based on ideal weather conditions:
#   A max temperature lower than 80 degrees but higher than 70.

#   Wind speed less than 10 mph.

#   Zero cloudiness.

narrowed_ideal_df = new_df.loc[(new_df['Max Temperature'] > 70) & 
                            (new_df['Max Temperature'] < 80) & 
                            (new_df['Cloudiness'] == 0), :]
# Drop any cities that do not meet the ideal conditions
narrowed_ideal_df = narrowed_ideal_df.dropna()

# Clean up new dataframe
narrowed_ideal_df.reset_index(inplace=True)
del narrowed_ideal_df['index']

narrowed_ideal_df.head()

,Unnamed: 0,City,Latitude,Longitude,Max Temperature,Humidity,Cloudiness,Wind Speed,Country
0,39,saint-philippe,-21.3585,55.7679,77.00,69,0,5.75,RE
1,40,tomatlan,19.9333,-105.2500,70.95,78,0,3.65,MX
2,63,batangafo,7.3008,18.2833,72.66,25,0,3.22,CF
3,99,bandarbeyla,9.4942,50.8122,70.72,76,0,14.74,SO
4,143,basco,20.4487,121.9702,71.76,77,0,26.02,PH

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [51]:
# Store variable named hotel_df
hotel_df = narrowed_ideal_df

# Add a "Hotel Name" column to the DF
hotel_df['Hotel Name'] = ''
hotel_df.head()

,Unnamed: 0,City,Latitude,Longitude,Max Temperature,Humidity,Cloudiness,Wind Speed,Country,Hotel Name
0,39,saint-philippe,-21.3585,55.7679,77.00,69,0,5.75,RE,
1,40,tomatlan,19.9333,-105.2500,70.95,78,0,3.65,MX,
2,63,batangafo,7.3008,18.2833,72.66,25,0,3.22,CF,
3,99,bandarbeyla,9.4942,50.8122,70.72,76,0,14.74,SO,
4,143,basco,20.4487,121.9702,71.76,77,0,26.02,PH,

In [61]:
# Set up a parameters dictionary
params = {
    'radius': 5000,
    'types': 'lodging',
    'keyword': 'hotel',
    'key': g_key
}

# base_url
base_url = 'https://maps.googleapis.com/maps/api/place/nearbysearch/json'

for index, row in hotel_df.iterrows():
    # Get longitude and latitude from hotel_df
    lat = row['Latitude']
    lng = row['Longitude']
    city = row['City']
    
    # Add keyword to params dict
    params['location'] = f'{lat}, {lng}'

    # Assemble url and make API request
    print(f"Retrieving Results for Index {index}: {city}.")
    response = requests.get(base_url, params=params).json()

    # extract results
    results = response['results']
    
    try:
        print(f"Closest hotel in {city} is {results[0]['name']}.")
        
        hotel_df.loc[index, 'Hotel name'] = results[0]['name']
        
    except (KeyError, IndexError):
        print('Missing field/result... skipping.')
    
#     time.sleep(1)
        
    print("------------")

Retrieving Results for Index 0: saint-philippe.
Closest hotel in saint-philippe is Les Embruns Du Baril.
------------
Retrieving Results for Index 1: tomatlan.
Closest hotel in tomatlan is Hotel Campanario.
------------
Retrieving Results for Index 2: batangafo.
Missing field/result... skipping.
------------
Retrieving Results for Index 3: bandarbeyla.
Closest hotel in bandarbeyla is JABIR HOTEL.
------------
Retrieving Results for Index 4: basco.
Closest hotel in basco is Amboy Hometel.
------------
Retrieving Results for Index 5: harper.
Closest hotel in harper is Grands' Guesthouse.
------------
Retrieving Results for Index 6: arraial do cabo.
Closest hotel in arraial do cabo is Mirante dos Anjos SuÃ­tes.
------------
Retrieving Results for Index 7: pilar.
Missing field/result... skipping.
------------
Retrieving Results for Index 8: atuona.
Closest hotel in atuona is CHALETS HANAKEE.
------------
Retrieving Results for Index 9: saint-pierre.
Closest hotel in saint-pierre is LODGE PALMAE.
------------
Retrieving Results for Index 10: odienne.
Closest hotel in odienne is HÃ”TEL SARAH.
------------
Retrieving Results for Index 11: honavar.
Closest hotel in honavar is Hotel Sagar Residency.
------------
Retrieving Results for Index 12: grand gaube.
Closest hotel in grand gaube is LUX Grand Gaube Resort & Villas.
------------
Retrieving Results for Index 13: coihaique.
Closest hotel in coihaique is Patagonia House.
------------
Retrieving Results for Index 14: puerto colombia.
Closest hotel in puerto colombia is Hotel El Emigrante.
------------
Retrieving Results for Index 15: lima.
Closest hotel in lima is Hotel Vox69 Suites.
------------
Retrieving Results for Index 16: raga.
Missing field/result... skipping.
------------
Retrieving Results for Index 17: sao joao da barra.
Closest hotel in sao joao da barra is OYO Pousada MediterrÃ¢neo.
------------
Retrieving Results for Index 18: axim.
Closest hotel in axim is Ankobra Beach.
------------
Retrieving Results for Index 19: gunjur.
Closest hotel in gunjur is Dalaba Eco-Lodge.
------------
Retrieving Results for Index 20: san carlos de bariloche.
Closest hotel in san carlos de bariloche is Huinid Pioneros Hotel.
------------
Retrieving Results for Index 21: pisco.
Closest hotel in pisco is HOSTAL MIRAMAR.
------------
Retrieving Results for Index 22: umm kaddadah.
Missing field/result... skipping.
------------
Retrieving Results for Index 23: nicoya.
Closest hotel in nicoya is Hotel DoÃ±a Marta.
------------
Retrieving Results for Index 24: saint-joseph.
Closest hotel in saint-joseph is "Plantation Bed and Breakfast.
------------
Retrieving Results for Index 25: tonj.
Missing field/result... skipping.
------------
Retrieving Results for Index 26: takoradi.
Closest hotel in takoradi is Best Western Plus Atlantic Hotel.
------------

In [63]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Latitude", "Longitude"]]

In [16]:
markers = gmaps.marker_layer(locations)
fig.add_layer(markers)
fig

Figure(layout=FigureLayout(height='420px'))